steps:
    - name: node:18.12.1
      entrypoint: npm
      args: ['install']
    - name: node:18.12.1
      entrypoint: npm
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy']
timeout: '1600s'
